export const SIZE_CONTENT_LARGE = 960;
export const SIZE_CONTENT_EXTRA_LARGE = 1200;

export const SIZE_THUMBNAIL_SCREEN_SMALL = 100;
export const SIZE_THUMBNAIL_SCREEN_MEDIUM = 125;
export const SIZE_THUMBNAIL_SCREEN_LARGE = 150;
export const SIZE_THUMBNAIL_SCREEN_EXTRA_LARGE = 175;

export const SIZE_ARTWORK_SCREEN_SMALL = 640;
export const SIZE_ARTWORK_SCREEN_MEDIUM = 768;
export const SIZE_ARTWORK_SCREEN_LARGE = 960;
export const SIZE_ARTWORK_SCREEN_EXTRA_LARGE = 1280;
