backend:
  name: git-gateway
  branch: master

media_library:
  name: uploadcare
  config:
    publicKey: 09634082642e628ffd99
  settings:
    autoFilename: true
    defaultOperations: '/resize/2048x/-/resize/1024x/-/resize/768x/-/resize/384x/-/quality/smart/'
collections:
  - name: 'sculptures'
    label: 'Sculptures'
    folder: '_posts/sculptures'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Path', name: 'path', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Year', name: 'year', widget: 'string' }
      - { label: 'Size', name: 'size', widget: 'string' }
      - { label: 'Media', name: 'media', widget: 'string' }
      - {
          label: 'Image',
          name: 'image',
          widget: 'image',
          media_library: { config: { multiple: true } },
        }
      - { label: 'Order', name: 'order', widget: 'number', default: 0 }
