backend:
  name: git-gateway
  branch: master

media_folder: "images/uploads"
collections:
  - name: "sculptures"
    label: "Sculptures"
    folder: "_posts/sculptures"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Year", name: "year", widget: "string"}
      - {label: "Size", name: "size", widget: "string"}
      - {label: "Media", name: "media", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Order", name: "order", widget: "number"}
