backend:
  name: git-gateway
  branch: master
media_library:
  name: cloudinary
  config:
    cloud_name: 'dgfapv7ud'
    api_key: 542466592693516
collections:
  - name: 'artworks'
    label: 'Artworks'
    folder: '_posts/artworks'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Category', name: 'category', widget: 'select', options: ['sculpture', 'collage', 'digital']}
      - { label: 'Path', name: 'path', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Year', name: 'year', widget: 'string' }
      - { label: 'Size', name: 'size', widget: 'string' }
      - { label: 'Media', name: 'media', widget: 'string' }
      - {
          label: 'Image',
          name: 'image',
          widget: 'image',
          config: { multiple: true },
        }
      - { label: 'Order', name: 'order', widget: 'number', default: 0 }
